### ISSUE TITLE
Support for interaction with message queues

### ISSUE THREAD

**Issue by nirpet** [SEEK-Jobs/pact-net#120]
Some of my DotNet services communicate with each other via Message Queues.
I saw that in the pact-jvm repository they defined a new pact file for interactions with message queues.
Is adding support for this new file (creating and verifing) planned to be added in the future?

**Comment by neilcampbell** [comment]
Hi @nirpet 
The goal is to have consistent support across all the Pact languages, however as you mentioned we are not there yet. We are hoping to have this support at some point, however I think this will be quite a while off.

**Comment by nirpet** [comment]
Hi, Thanks for the reply.
Is it possible to be added as a contributor in order to create this feature?

**Comment by neilcampbell** [comment]
@nirpet The best way to contribute is via forking and a PR. Heads up we now use the ruby standalone core (https://github.com/pact-foundation/pact-ruby-standalone) as the Pact engine, so in order to get this working in .NET we will need to get it working on the ruby standalone core as well. Our goal is for all the language implementations to use the same core, so that we have less feature divergence.

Whilst at the moment we use the Ruby core, we are planning to move to the Rust implementation at some point, as the goal is for everything to use that.

**Comment by nirpet** [comment]
Okay, thanks!
