### ISSUE TITLE
Prevent use of a regular expression where the example does not match the regular expression

### ISSUE THREAD

**Issue by bethesque** [SEEK-Jobs/pact-net#44]
Not sure if the .net implementation covers this, so raising an issue to ensure it gets addressed if it hasn't already.

For example, it should not be possible to specify that a phone number must match /^\d+$/, but give an example of "foo".

**Comment by neilcampbell** [comment]
Good point! We still have not finished v2/regex matching, so will add a test for that scenario.

**Comment by bethesque** [comment]
:+1:

**Comment by robertfall** [comment]
Just wanted to find out if work on v2 and matchers is still happening or whether it's stalled as there have been no commits on the branches for some time. 

Our team would like to use the matchers functionality as other language platforms support it. Is this work ongoing and is the work that was done still relevant? If we were to look at implementing the matcher functionality should we branch from master? Who can we chat to around API design?

**Comment by neilcampbell** [comment]
Hi @robertfall 
Thanks for getting in touch!

AFAIK there is no one currently doing any work to get v2 matching working. Issue https://github.com/SEEK-Jobs/pact-net/issues/9 contains a whole bunch of info about what is required to get it working, so have a read of that one. If you a interested in having a crack at implementing, create a fork (and use the version-2 branch) and go from there. Yep the work is still relevant. I just merged master into version-2, so you should be good to go.

As far as API design goes, you can add comments to issue https://github.com/SEEK-Jobs/pact-net/issues/9 and we can all chat about it. The API of the.NET version has taken a lot of influence from the other languages, so it's probably worth having a look at their API surface area. The pact specification https://github.com/pact-foundation/pact-specification/tree/version-2 project will also help here.

Unfortunately I don't have the bandwidth at this time to tackle this myself, otherwise I would. I also haven't had any desperate need for partial matching to be honest, so that has put it on the back burner.

**Comment by robertfall** [comment]
Thanks @neilcampbell.

I'll have a look at the other language APIs and see what I can do. :smile:

**Comment by ChuanChuanLaw** [comment]
Hi,

I am new to Pact Net and is currently trying to create a spike project with flexible matching features. According to the forum thread, seems like flexible matching has not being implemented like the Ruby and JVM features.

Therefore, we checked out Abhaya's branch. However, flexible matching does not seem to be working too. Although JSON file like below is being generated:

 "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "Count": "abc"
        },
        "matchingRules": {
          "$.body.Count": {
            "regex": "\\w+"
          }
        }
      }

When we change the regex to \d+, the Provider test will passed as well.

Please advice if flexible matching for Pact Net can be used now, and if so, which branch should we be using.

Thanks heaps.

Chuan

**Comment by neilcampbell** [comment]
Hi @ChuanChuanLaw.
No flexible matching is not yet implemented in .NET. The version-2 branch is a work in progress branch to begin implementing it. When it becomes available and ready to use, it will be in master.

**Comment by neilcampbell** [comment]
Now that we are using the Ruby standalone core, this feature is implemented there and has been tested to work correctly with Pact-Net.
