### ISSUE TITLE
Working with types or regex

### ISSUE THREAD

**Issue by karlgjertsen** [SEEK-Jobs/pact-net#64]
Hi Guys,

Where can I find samples of how to create the pact file with types instead of fixed values?

I wan tot use this in a project, but I won't be able to unless I can find a way to work with types instead of fixed data.

Thanks,

Karl

**Comment by neilcampbell** [comment]
Hi @karlgjertsen 
Is this the kind of the thing you are after https://github.com/SEEK-Jobs/pact-net/blob/master/Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs ?

Also wanted to mention that we do not support partial or regex matching at this time. See https://github.com/SEEK-Jobs/pact-net/issues/9

**Comment by karlgjertsen** [comment]
I am trying to add the PACT tests to my API Provider, but I'm finding the tests are too brittle. For example, I might return an integer value, which may change. I only want to test it for an integer and not an actual value.

I'm using the GitHub API as my test service. I have written the consumer tests, which work ok. In the provider tests, I am calling the live API, but what if a value changes, example: public_repos (int) might change.

Do I need to add something to the PactVerifier to overload how it does the validation? I can't find any samples or documentation for this.

I am so close to making this work, but I feel that must be missing something!

**Comment by neilcampbell** [comment]
Yep, I completely understand.
v1 of Pact is all about testing providers where you can control the state and put the system in a deterministic state.
v2 is aiming to work with the scenarios you mention.

At this time PactNet does not support v2 of the Pact specification.

As a side note your contract should only specify the values that your consumer actually requires, so if you don't use `public_repos` it should not be in the contact and wont be validated on the provider side.

If you want to use PactNet now you have two options:
1. Setup an account in Github (because you are testing the Github api) which has a very specific state, that you can completely control and that will not change. Then use that account data for your consumer test. This should give you the deterministic state you require.
2. Consider having a look at the Pact v2 spec https://github.com/pact-foundation/pact-specification, https://github.com/SEEK-Jobs/pact-net/tree/version-2 v2 branch and https://github.com/SEEK-Jobs/pact-net/issues/9 and help out in implementing the v2 specification.

**Comment by karlgjertsen** [comment]
Thank you for the answer Neil

I will try to schedule some time and then see what I can help with.
