### ISSUE TITLE
[Idea] Automatic record/replay mocks

### ISSUE THREAD

**Issue by etiago** [SEEK-Jobs/pact-net#67]
We recently started using pact-net at work and I'm slightly bothered by how much manual work is involved in creating the mocks and handling the resulting files.

I was thinking whether it would be a good idea (and whether someone thought about it) to create some sort of proxy generic mock which could be started in "record mode" and to which we would then direct our services. This proxy mock would (based on a config file) forward the requests to the actual service and then transport the response back to the actual service. This request/response interaction pair could then be saved as, e.g., a JSON file. Then, we would be able to start the proxy mock in a "replay mode" where it's simply replying to requests based on what it has recorded. This way we would avoid having to write the mock services ourselves and instead take the current snapshot of the provider as the "valid contract" upon which we base all our future test runs.

Has anyone thought about this? Do you see value on it if, e.g., I was to work on something along these lines?

**Comment by neilcampbell** [comment]
Hey @etiago 
Thanks for getting in touch, and I can appreciate there is a bit of work to get Pact up and running.

It is actually something we have chatted about and there are actually already tools which can do this should it fit your use case better (see https://github.com/vcr/vcr and https://github.com/matthew-cochran/Betamax.Net). Pact kind of takes the reverse philosophy (see https://github.com/realestate-com-au/pact/wiki/FAQ#how-does-pact-differ-from-vcr).

With Pact the consumer defines only the fields it cares about in the req and res, nothing more, nothing less and as such that means service providers can validate the impact changes have on the consumers (given that all consumers use Pact and properly define the contracts), rather than assuming pretty much all changes are breaking changes.




The idea behind specifying your own interaction, is that you should only specify the things you specifically care about (see 


We have had chats about this, however it's not the primary use case for Pact.
The idea behind pact is to use it as a replaceme

**Comment by etiago** [comment]
@neilcampbell it makes sense, thanks for the pointers! Such a pity that Betamax.Net seems to be abandoned but I can understand that Pact-Net takes a different spin on it. :+1:

**Comment by neilcampbell** [comment]
@etiago I have a feeling other VCR ports for .NET exist, otherwise fork it and it's all yours :)
