### ISSUE TITLE
Does not work with Nancy 1.4.3

### ISSUE THREAD

**Issue by xlegalles** [SEEK-Jobs/pact-net#72]
Hi,
I had the last Nancy 1.4.3 and the consumer test was raising an exception (timeout on the ClearInteractions). I have checked all other dependencies but it fails because of Nancy: it works with the 0.23.1. I did not check with other versions. At least you should update the documentation. 

Btw, thank you for this very nice library.
Xavier

**Comment by neilcampbell** [comment]
@xlegalles Thanks for reporting the issue. I will take a look to see how it can be fixed.

**Comment by neilcampbell** [comment]
So I just extracted the sample inside the Pact solution and installed Nancy 1.4.3 with Nancy.Hosting.Self 1.4.1 and everything worked fine.

I then tried just updating Nancy to 1.4.1 and leaving Nancy.Hosting.Self 0.23.1 and that failed the test. I believe this issue is related to not having updated Nancy.Hosting.Self alongside Nancy. The direct dependency Pact has is with Nancy.Hosting.Self and not Nancy, if you want to update Nancy you should be updating it via Nancy.Hosting.Self.

Can you try updating Nancy.Hosting.Self as well?

**Comment by neilcampbell** [comment]
No problems at all!
