### ISSUE TITLE
Ordering of elements in the response

### ISSUE THREAD

**Issue by paulmarshall** [SEEK-Jobs/pact-net#90]
Should PACT be sensitive to the order of elements within a response ?

**Comment by neilcampbell** [comment]
@paulmarshall When you say elements in a response are you referring to a json key value pair or are you talking about an array element?

If it is an array element you are speaking about then yes Pact is sensitive to order see https://github.com/pact-foundation/pact-specification/blob/version-1.1/testcases/response/body/array%20in%20different%20order.json

**Comment by paulmarshall** [comment]
@neilcampbell Here is an example.

If I expect an API to return details of an "order" as follows:
```
{
"billingAddress": { "firstline": "83 Lincoln Road"},
"delivery": { "cost": "8"}
}
```

But instead I get:
```
{
"delivery": { "cost": "8"},
"billingAddress": { "firstline": "83 Lincoln Road"}
}
```

Then Pact will treat this interaction as a failure. I can maybe understand this for an array element (where  ordering has been applied and this needs to be preserved), but not for properties on a type whose ordering is ignored when de-serialised.

**Comment by neilcampbell** [comment]
@paulmarshall PactNet should not fail under this scenario, so my guess is there is something else that is causing the failure. I have had others ask the same question, and every time so far it has been due to a different failure in the interaction (un-related to order). The order just makes it hard to see.

Is that the full order, or are there other fields returned?

I would try taking both items in the diff and align the orders in a diff tool and check if there is nothing else different.

**Comment by neilcampbell** [comment]
Also this is the test case that proves it works correctly https://github.com/pact-foundation/pact-specification/blob/version-1.1/testcases/response/body/keys%20out%20of%20order%20match.json
